# Generated by Django 5.2.4 on 2025-07-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/covers/default.jpg",
                upload_to="profile_images/covers/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.png",
                upload_to="profile_images/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sport",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="grad_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
