# Generated by Django 5.2.4 on 2025-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_comment_follow_like_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="post_videos/"),
        ),
    ]
